### PR TITLE
Use hashicorp's terraform-json to parse Plan

### PR DESCRIPTION
**Pull request by mouellet**
## All Submissions:
-------------------------------------
* [YES] Have you followed the guidelines in our Contributing [document](./CONTRIBUTING.md)?
* [YES] Have you added an explanation of what your changes do and why you'd like us to include them?
* [YES] I have updated the documentation accordingly.
* [YES] I have added tests to cover my changes.
* [YES] All new and existing tests passed.
* [YES] My code follows the code style of this project.
* [YES] I ran lint checks locally prior to submission.
* [YES] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

## What is the current behavior?
-------------------------------------

A plan struct w/ only `ResourceChanges` mapped.

## What is the new behavior?
-------------------------------------

Goal of this PR is to allow unit testing on plan output changes, as some might contain logic or conditionals.

- Bump github.com/gruntwork-io/terratest to v0.32.8
- Add github.com/hashicorp/terraform-json as dependency (it contains a backward compatible but fully mapped struct for Plans)

The UnitTestFixture's PlanAssertions can now be used to test any part of the plan.

## Does this introduce a breaking change?
-------------------------------------
- [NO]

## Any relevant logs, error output, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

## Other information
-------------------------------------

### CODE REVIEW

**Comment by nmiodice** [comment]
I love the changes. I pulled your code and needed to make the following change to the sample in order for it to run. I should go ahead and add these to the CI, but until then... Mind making these changes?

```text
diff --git a/samples/azure/main.tf b/samples/azure/main.tf
index 7dccf16..c8462f5 100644
--- a/samples/azure/main.tf
+++ b/samples/azure/main.tf
@@ -1,9 +1,16 @@
 ##
 # Providers
 ##
+terraform {
+  required_providers {
+    azurerm = {
+      source  = "hashicorp/azurerm"
+      version = "=2.46.0"
+    }
+  }
+}
+
 provider "azurerm" {
-  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
-  version = "=2.0.0"
   features {}
 }
```

**Comment by nmiodice** [comment]
Also I love the addition of `github.com/hashicorp/terraform-json`. Would you be able to add this to the integration test interface as well so that we have a consistent API? The change should be similar based on your approach for `unit`

https://github.com/microsoft/terratest-abstraction/blob/master/integration/integration.go#L20

**Comment by mouellet** [comment]
> Also I love the addition of `github.com/hashicorp/terraform-json`. Would you be able to add this to the integration test interface as well so that we have a consistent API? The change should be similar based on your approach for `unit`
> 
> https://github.com/microsoft/terratest-abstraction/blob/master/integration/integration.go#L20

Actually, the result from `terraform output -json` is already transformed into a key=value map upstream in terratest (https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/output.go#L309). I don't think we should change that...

**Review by nmiodice — APPROVED** [review]
Ship It!
```
       _~
    _~ )_)_~
    )_))_))_)
    _!__!__!_
    \______t/
  ~~~~~~~~~~~~~
```

**Pull request merged**
